### ISSUE TITLE
Allow Workflow API to bypass some beta api criteria

### ISSUE THREAD

**Issue by nyemade-uversky** [dapr/proposals#30]
# Allow Workflow API to bypass some beta api criteria

This is a proposal for allowing Dapr Workflow (WF) to reach beta status without having to meet the criteria that is irrelevant to the workflow api specifically [API Lifecycle](https://github.com/dapr/proposals/blob/main/templates/lifecycle.md#beta). 

## Background
Dapr WF differs from other Dapr APIs in that there is only one component implamentation of the API, the built-in actor-based wf engine. Therefore this makes it difficult to meet stable criteria that related to the following:

- [ ] Minimum of N (three?) implementations of this building block 
- [ ] Conformance tests updated to match any API changes that have been made
- [ ] Conformance tests exercise both positive and negative cases 
- [ ] Certification tests for implementations 

I propose we allow the Dapr WF to mimic the stability process of Dapr Actors, and remove these criteria as stable requirements for the the workflow feature. Without doiong so, workflow will not have a clear path to beta and overall stability.

**Comment by nyemade-uversky** [comment]
@yaron2 , @msfussell, @artursouza and @paulyuk would you be able to give this a look? I'd like to get the stable process for wf worked out soon so we can shoot for the right beta criteria for 1.12

**Comment by yaron2** [comment]
Supportive, please see comment here https://github.com/dapr/proposals/pull/29#issuecomment-1623997105.
