### ISSUE TITLE
Remove Conformance Test Requirement for Bindings Components

### ISSUE THREAD

**Issue by cicoyle** [dapr/proposals#37]
According to the [docs on Certification Lifecycle](https://docs.dapr.io/operations/components/certification-lifecycle/), in order for a component to become `Beta` it must have a record of a `conformance test`.

I **propose** removing this requirement, that of having a conformance test be required for binding components specifically. This would entail updating the docs and allowing the docs to be the source of truth for the community and maintainers to use going forward and build consensus upon.

- A _reason_ this change is requested, is that according to @ItalyPaleAle, some components don't have anything to conform to and test. [You can see that with the Zeebe Component test PR that was closed here](https://github.com/dapr/components-contrib/pull/3117).
- This would be of _benefit_ to the Dapr community in that it would save a Github task runner resource since its not adding much value according to @berndverst in the same PR link provided above.

This would ultimately _benefit_ the Dapr community in that it would also allow the users to trust that what is documented in [docs.dapr.io](https://docs.dapr.io/) is going to be upheld by the community and maintainers, and that there are no unspoken rules they need to abide by.

**Comment by berndverst** [comment]
I support this. Thanks for formalizing @cicoyle.

The rule that a brand new component with certification test cannot be immediately until one additional release after introduction still applies.

So the following situations will apply:
Binding component without certification test: Alpha
Brand new binding component with Certification test: Beta (will automatically be stable in next release after)
Existing binding component with certification test added: stable.

The guideline requirement that certification tests must cover all metadata properties also applies still.

Going from Alpha to Stable can be done for binding components sold through an adequate certification test.

**Comment by ItalyPaleAle** [comment]
Thanks @cicoyle! I support the proposal as clarified by Bernd's message.

In the specific case, this applies to bindings only, which are components that are very frequently one-offs and aren't generally interchangeable (we have _some_ bindings that can be used _somewhat_ interchangeably, such as state stores or pubsub components implemented as bindings, but those are the exception).

The rationale behind the requirement for conformance tests is that we want all components to behave the same way. This should still apply to all other component classes, including state stores, pubsubs, secret stores, etc, which are standardized in the behavior. In the case of one-off bindings, there's not much value that a conformance test can be provided.

Given the above, I agree that **for one-off bindings**, the presence of a **comprehensive certification test** can supersede the requirement for a conformance test. (This is symmetrical to the opposite requirement we have for other components, where we require that certification tests do not re-implement what's already tested by conformance tests)

To clarify:

- This only applies to bindings which are "one-off", meaning that don't belong to common types of bindings.
- As explained by Bernd above, this will allow a one-off binding to become stable by skipping the requirement for a conformance test.
- It does **not** allow a binding to become beta without a conformance or certification test.
- Whether a binding is a "one-off" one, which qualifies it for the exception above, is the maintainers' discretion.

**Comment by berndverst** [comment]
> Thanks @cicoyle! I support the proposal as clarified by Bernd's message.
> 
> In the specific case, this applies to bindings only, which are components that are very frequently one-offs and aren't generally interchangeable (we have _some_ bindings that can be used _somewhat_ interchangeably, such as state stores or pubsub components implemented as bindings, but those are the exception).
> 
> The rationale behind the requirement for conformance tests is that we want all components to behave the same way. This should still apply to all other component classes, including state stores, pubsubs, secret stores, etc, which are standardized in the behavior. In the case of one-off bindings, there's not much value that a conformance test can be provided.
> 
> Given the above, I agree that **for one-off bindings**, the presence of a **comprehensive certification test** can supersede the requirement for a conformance test. (This is symmetrical to the opposite requirement we have for other components, where we require that certification tests do not re-implement what's already tested by conformance tests)
> 
> To clarify:
> 
> * This only applies to bindings which are "one-off", meaning that don't belong to common types of bindings.
> * As explained by Bernd above, this will allow a one-off binding to become stable by skipping the requirement for a conformance test.
> * It does **not** allow a binding to become beta without a conformance or certification test.
> * Whether a binding is a "one-off" one, which qualifies it for the exception above, is the maintainers' discretion.

The point on one-off components is a good point.

There are a few groups of bindings which perform similar tasks - those should continue to have conformance tests. However there are plenty of these one-off bindings for which it simply does not make sense.

so I agree it is up to the contrib maintainers to designate a binding component as one-off and thereby skip the conformance test requirement for stable certification.

**Comment by ItalyPaleAle** [comment]
Additional @dapr/maintainers-components-contrib to chime in

**Comment by cicoyle** [comment]
I am with yall on it being up to the maintainers to designate which binding components are one-offs, but how will that be relayed to community members? Will maintainers just keep up on when a new one-off component PR comes up and explicitly note that to the community member? (in addition to a generic note in the docs on it)

**Comment by ItalyPaleAle** [comment]
We’ll document the component’s status in the docs, and when present the metadata.yaml files - those are the ultimate sources of truth. Paper trails should be left in GitHub issues.

Also, one last thing to stress is that in absence of a conformance test, the certification tests must be comprehensive to include all methods offered by the component (eg all bindings’ operations)

**Comment by berndverst** [comment]
@cicoyle there should be an issue filed to track making a component beta or stable. Maintainers could then chime in on that issue.

yes we as maintainers who are also the ones who must merge PRs do keep up with those issues! And this is something that will be self evident for us as maintainers - there isn't a whole lot of ambiguity.

In an ideal world many of these binding groups would be their own building block components - but that's a lot of work and something that can't be changed for legacy reasons.

**Comment by berndverst** [comment]
The docs will ultimately (in the future) be generated from the metadata yaml files. And the metadata yaml files require a contrib maintainer to be merged. But as far as tracking the requirement I recommend:

1. Open a tracking issue for making a binding stable
2. Wait for a maintainer to chime in on conformance test requirement if unclear
3. Meanwhile PR work for the certification test (which must cover metadata options and the various binding operations) can begin in parallel.

**Comment by artursouza** [comment]
I agree to have the exception for conformance tests being required to be stable for bindings only. Conformance tests have value to validate equal behavior cross implementations.

**Comment by ItalyPaleAle** [comment]
@cicoyle we have enough maintainer votes to consider this approved!

Would you be willing to open the PR in the docs repo to update the requirements?

A TLDR is: bindings for which a conformance test doesn't provide additional value can become stable without the requirement for a conformance test, as long as the other requirements (most notably a comprehensive certification test) are met. Those components can skip the beta stage and become stable right away once they meet all other requirements.

**Comment by cicoyle** [comment]
This is complete. Thanks yall 🚀
