### ISSUE TITLE
Where will proposal discourse happen?

### ISSUE THREAD

**Issue by olitomlinson** [dapr/proposals#5]
> The author(s) address questions/comments from the community in the proposal and adjust the proposal based on feedback

https://github.com/dapr/proposals#proposal-process

As someone who reviews proposals (which are typically housed in a GH issue), I like to go to a single place to review the commentary and discourse around that matter. I don't see in this new proposal process any recommendation for where the discourse must/could/should happen?

Suggestions
- Raise a _single_ GH issue to accompany each proposal
- Create a _single_ Discord forum post for each proposal
- Use the 'conversation' section of a PR for each proposal

**Comment by yaron2** [comment]
We were looking to anchor that as PR comments. Do you see downsides to that?

**Comment by olitomlinson** [comment]
@yaron2 yep I think conversation comments is just fine :)
